services:
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
  qcard-server:
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 80:8080
    depends_on:
      - redis
